name: Trigger workspace changes

on:
    # Trigger the workflow on push or pull request,
    # but only for the main branch
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    changes:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
            checks: write
            pull-requests: read
        outputs:
            src: ${{ steps.changes.outputs.ads_sandbox }}
            infra: ${{ steps.changes.outputs.portofolio }}
        steps:
            - uses: actions/checkout@v3
            - uses: dorny/paths-filter@v2
              id: changes
              with:
                  filters: |
                      ads_sandbox:
                        - 'apps/ads-sandbox/**'
                      portofolio:
                        - 'apps/portofolio/**'

    ads_sandbox:
        needs: changes
        if: ${{ needs.changes.outputs.src == 'true' }}
        uses: irfanmaulana007/irfanmaulana007/apps/ads-sandbox/.github/workflows/staging.yml@main
        # runs-on: ubuntu-latest
        # steps:
        #     - uses: actions/checkout@v3
        #     - run: ./apps/ads-sandbox/.github/workflows/staging.yml

    portofolio:
        needs: changes
        if: ${{ needs.changes.outputs.infra == 'true' }}
        uses: irfanmaulana007/irfanmaulana007/apps/portofolio/.github/workflows/staging.yml@main
        # runs-on: ubuntu-latest
        # steps:
        #     - uses: actions/checkout@v3
        #     - run: ./apps/portofolio/.github/workflows/staging.yml
