name: Trigger workspace changes

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    changes_check:
        name: Changes Check
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
            checks: write
            pull-requests: read
        outputs:
            src: ${{ steps.changes.outputs.ads_sandbox }}
            infra: ${{ steps.changes.outputs.portofolio }}
        steps:
            - uses: actions/checkout@v3
            - uses: dorny/paths-filter@v2
              id: changes
              with:
                  filters: |
                      ads_sandbox:
                        - 'apps/ads-sandbox/**'
                      portofolio:
                        - 'apps/portofolio/**'

    test_build_ads_sandbox:
        name: Test build ads-sandbox
        needs: changes_check
        if: ${{ needs.changes_check.outputs.src == 'true' }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./apps/ads-sandbox/.github/actions/staging

    test_build_portofolio:
        name: Test build portofolio
        needs: changes_check
        if: ${{ needs.changes_check.outputs.src == 'true' }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./apps/portofolio/.github/actions/staging
